app/__init__.py
from logging import debug
import os 

from flask import Flask, app

def create_app():
    app= Flask(__name__)

    app.config.from_mapping(
        SECRET_KEY = 'MiLLave',
        DATABASE_HOST = os.environ.get('FLASK_DATABASE_HOST'),
        DATABASE_PASSWORD = os.environ.get('FLASK_DATABASE_PASSWORD'),
        DATABASE_USER = os.environ.get('FLASK_DATABASE_USER'),
        DATABASE = os.environ.get('FLASK_DATABASE')
    )

    from . import db
    from . import auth
    from . import views
    from . import siembra
    from . import colgado
    from . import cosecha
    

    app.register_blueprint(colgado.bp)
    app.register_blueprint(cosecha.bp)
    app.register_blueprint(siembra.bp)
    app.register_blueprint(auth.bp)
    app.register_blueprint(views.bp)
    db.init_app(app)
    
    @app.route('/inicio')
    def inicio():
        return 'Hola'

    return app

app/auth.py
import functools
from os import error
from flask import(
    Blueprint, flash, g, render_template, request, url_for, session
)
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import redirect
from app.db import get_db

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/register', methods=['GET','POST'])
def register():
    db, c = get_db()
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        position = request.form['position']
        error = None
        c.execute(
            'select id from user where username = %s', (username,)
        )
        
        if not username:
            error = 'Usuario es requerido'
        if not password:
            error = 'Contraseña requerida'
        if not position:
            error = 'Rol requerido'
        elif c.fetchone() is not None:
            error = 'Usuario {} se encuentra registrado'.format(username)

        if error is None:
            c.execute(
                'insert into user (username, password, position) values (%s, %s, %s)',
                (username, generate_password_hash(password), position)
            )
            db.commit()

            return redirect(url_for('auth.login'))
    
        flash(error)
    c.execute(
            'select * from rol'
        )
    roles = c.fetchall()
    return render_template('auth/register.html', roles=roles)

@bp.route('/login', methods= ['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db, c = get_db()
        error = None
        c.execute(
            'select * from user where username = %s', (username,)
        )
        user = c.fetchone()

        if user is None:
            error = 'Usuario y/o contraseña inválida.'
        elif not check_password_hash(user['password'],password):
            error = 'Usuario y/o contraseña inválida'
        
        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('index.index'))

        flash(error)
    
    return render_template('auth/login.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        db, c = get_db()
        c.execute(
            'select * from user where id = %s', (user_id,)
        )
        g.user = c.fetchone()

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view 

@bp.route('logout')
def logout():
    session.clear()
    return redirect(url_for('auth.login'))

app/views.py
from os import error
import app
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from werkzeug.exceptions import abort
from app import db
from app.auth import login_required
from app.db import get_db
from jinja2  import TemplateNotFound
import calendar


bp = Blueprint('index', __name__)

@bp.route('/')
@login_required
def index():
        # Detecta la pagina actual
        # segment = get_segment( request )
        # Serve the file (if exists) from app/templates/FILE.html
    db, c = get_db()
    c.execute(
        'SELECT o.nombreOrigen, SUM(cuelgas) as SumaCuelgas FROM colgados c'
        ' inner join origenes o on c.origen=o.idOrigen'
        ' group by origen'
    )
    cuelgas_origenes = c.fetchall()
    labels= []
    values= []
    for cuelga_origen in cuelgas_origenes:
        values.append(int(cuelga_origen['SumaCuelgas']))
        labels.append(cuelga_origen['nombreOrigen'])

    c.execute(
        'select SUM(kgsCosechado) as TotalCosechado, camada from cosechas'
        ' group by camada'
    )
    camada_cosechado = c.fetchall()
    l= []
    v= []
    for cosechado in camada_cosechado:
        v.append(int(cosechado['TotalCosechado']))
        l.append(cosechado['camada'])
        
    return render_template('index.html', labels=labels, values=values, l=l, v=v)
    

    # except TemplateNotFound:
    #     return render_template('page-404.html'), 404



# Helper - Extrae el nombre de la pagina actual mediante el request
# def get_segment( request ): 

#     try:

#         segment = request.path.split('/')[-1]

#         if segment == '':
#             segment = 'index'

#         return segment    

#     except:
#         return None  

app/templates/base.html
<!DOCTYPE html>
<title>{% block title %}{% endblock %} - CROSAM</title>
<link rel="stylesheet" href="{{ url_for("static", filename = "css/style.css") }}">


<nav>
    <h1>CROSAM LIMITADA</h1>
    <ul>
        {% if g.user %}
            <li>
                <span> {{ g.user['username'] }}</span>
            </li>
            <li>
                <span>
                    <a href="{{url_for('auth.logout') }}">Cerrar Sesión</a>
                </span>
            </li>
        {% else %}
            <li>
                <a href="{{ url_for('auth.register' )}}">Registrarse</a>
            </li>
            <li>
                <a href="{{ url_for('auth.login' )}}">Iniciar Sesión</a>
            </li>
            
        {% endif %}
    </ul>
</nav>

<section class="content">
    
    <header>
        {% block header %}Menus{% endblock %}
    </header>
    {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
    {% endfor%}
    {% block content%} {% endblock %}
</section>

app/templates/colgado/create.html
<h1>CREATE COLGADO</h1>

app/templates/colgado/index.html
{% extends "layouts/base.html" %}

{% block title %} Colgado {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<link href="/static/assets/css/style.css" rel="stylesheet" />
{% endblock stylesheets %}

{% block content %}

    <h1>Modulo Colgado</h1>

        <form method="post">
            <div class="form-group">
                <div class="form-row">
                    <div class="col-1">
                        <input type="text" class="form-control" placeholder="Linea" name="linea" id="linea" required>
                    </div>
                    <div class="col-3">
                        <input type="text" class="form-control" placeholder="Sistema" name="sistema" id="sistema" required>
                    </div>
                    <div class="col-1">
                        <input type="text" class="form-control" placeholder="Cuelgas" name="cuelgas" id="cuelgas" required>
                    </div>
                    <div class="col-2">
                        <input type="date" class="form-control" placeholder="Fecha" name="fechaColgado" id="fechaColgado" required>
                    </div>
                    <select class="form-control col-2" name="origen" class="select-form" required> 
                    
                        <option value="" selected hidden >Origen</option>
                        {% for origen in origenes %}
                            <option value="{{ origen.idOrigen }}">{{ origen.nombreOrigen }} </option>    
                        {% endfor %}
                    </select>
                    <button type="submit" class="btn btn-guardar-colgado">Guardar</button> 
                </div>
            {% for message in get_flashed_messages() %}
                <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% endfor %}    
            </div>
          </form>
        
   

    <table class="table">
        <thead>
            <tr>
                <th>Linea</th>
                <th>Sistema</th>
                <th>Cuelgas</th>
                <th>Fecha de Colgado</th>
                <th>Origen</th>
            </tr>
        </thead>
        <tbody>
            {% for colgado in colgados %}
               <tr>
                   <td>{{ colgado.linea }}</td>
                   <td> {{ colgado.sistema }}</td>
                   <td>{{ colgado.cuelgas }}</td>
                   <td>{{ colgado.fechaColgado.strftime('%d-%m-%Y') }}</td>
                   <td>{{ colgado.nombreOrigen }}</td>
                   <td class="btn-colgado" style="border-top: 0px;">
                        <a href="{{ url_for('colgado.update', id=colgado['idColgado'])}}" class="action">Editar</a>
                   </td>
                   <td class="btn-colgado" style="border-top: 0px;">
                    <a href="{{url_for('colgado.delete', id = colgado['idColgado'])}}" class="text-danger">Eliminar</a>
               </td>
               </tr> 
            {% endfor %}
        </tbody>
    </table>
    

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}

app/templates/colgado/update.html
<link href="/static/assets/css/black-dashboard.css?v=1.0.0" rel="stylesheet" />

<form method="post" class="container-fluid">
    
    <div class="form-group row">
        <div class="col-sm-2">
            <label >Linea</label>
            <input type="text" class="form-control" value="{{ colgado.linea }}" name="linea" id="linea">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label >Sistema</label>
            <input type="text" class="form-control" value="{{ colgado.sistema }}" name="sistema" id="sistema">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label >Cuelga</label>
            <input type="text" class="form-control" value="{{ colgado.cuelgas }}" name="cuelgas" id="cuelgas">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-2">
            <label >Fecha de Colgado</label>
            <input type="date" class="form-control" value="{{colgado.fechaColgado}}" name="fechaColgado" id="fechaColgado">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <select class="form-control " name="origen" class="select-form" required> 
                <option value="" selected hidden >Origen</option>
                {% for origen in origenes %}
                    <option value="{{ origen['idOrigen'] }}">{{ origen.nombreOrigen }} </option>    
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-1">
            <a href="{{url_for('colgado.index')}}">Volver</a>
        </div>
        <div class="col-sm-2">
            <input type="submit" value="Guardar">
        </div>
    </div>

    
</form>

app/templates/cosecha/index.html
{% extends "layouts/base.html" %}

{% block title %} Colgado {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}<link href="/static/assets/css/style.css" rel="stylesheet" />{% endblock stylesheets %}

{% block content %}

    <h1>Modulo Cosecha</h1>
    
    <form method="post">
        <div class="form-group">
            <div class="form-row">
                <div class="col-md-2">
                    <input type="date" class="form-control" placeholder="Fecha Cosecha" name="fechaCosecha" id="fechaCosecha" required>
                </div>
                <div class="col-2">
                    <input type="text" class="form-control" placeholder="Código de Centro" name="codigoCentro" id="codigoCentro" required>
                </div>
                <div class="col-1">
                    <input type="text" class="form-control" placeholder="Nro Guía" name="nroGuia" id="nroGuia" required>
                </div>
                <div class="col-1">
                    <input type="text" class="form-control" placeholder="Folio" name="folio" id="folio" required>
                </div>
                <div class="col-1">
                    <input type="text" class="form-control" placeholder="Linea (Guía)" name="linea_guia" id="linea_guia" required>
                </div>
                <div class="col-1">
                    <input type="text" class="form-control" placeholder="Camada" name="camada" id="camada" required>
                </div>
                <div class="col-1">
                    <input type="text" class="form-control" placeholder="Nro Cuelga" name="nroCuelga" id="nroCuelga" required>
                </div>
                <div class="col-1">
                    <input type="text" class="form-control" placeholder="Metro Red" name="metroRed" id="metroRed" required>
                </div>
                <div class="col-1">
                    <input type="text" class="form-control" placeholder="MaxiSaco" name="maxiSaco" id="maxiSaco" required>
                </div>
                <div class="col-2">
                    <input type="text" class="form-control" placeholder="Kgos Coeschado" name="kgsCosechado" id="kgsCosechado" required>
                </div>
                <div class="col-1">
                    <input type="text" class="form-control" placeholder="Condición" name="condicion" id="condicion" required>
                </div>
                <select class="form-control col-2" name="sembradora" class="select-form" required> 
                    <option selected hidden >Servicio</option>
                    {% for sembradora in sembradoras %}
                        <option value="{{ sembradora.idSembradora }}">{{ sembradora.nombreSembradora }} </option>    
                    {% endfor %}
                </select>
                <div class="col-1">
                    <input type="text" class="form-control" placeholder="Patente" name="patente" id="patente" required>
                </div>
                <select class="form-control col-2" name="destino" class="select-form" required> 
                
                    <option selected hidden >Destino</option>
                    {% for destino in destinos %}
                        <option value="{{ destino.idDestino }}">{{ destino.nombreDestino }} </option>    
                    {% endfor %}
                </select>
                <button type="submit" class="btn  btn-guardar-cosecha">Guardar</button> 
            </div>
        {% for message in get_flashed_messages() %}
            <div class="alert alert-danger" role="alert">{{ message }}</div>
        {% endfor %}    
        </div>
      </form>
    <table class="table">
        <thead>
            <tr>
                <th>Fecha Cosecha</th>
                <th>Codigo Centro</th>
                <th>Nro Guía</th>
                <th>Folio</th>
                <th>Linea (Guía)</th>
                <th>Camada</th>
                <th>Nro Cuelga</th>
                <th>Metro Red</th>
                <th>MaxiSaco</th>
                <th>Kgs Cosechado</th>
                <th>Condición</th>
                <th>Servicio</th>
                <th>Patente</th>
                <th>Destino</th>
            </tr>
        </thead>
        <tbody>
            {% for cosecha in cosechas %}
            <tr>
                <td>{{ cosecha.fechaCosecha.strftime('%d-%m-%Y') }}</td>
                <td>{{ cosecha.codigoCentro }}</td>
                <td>{{ cosecha.nroGuia }}</td>
                <td>{{ cosecha.folio }}</td>
                <td>{{ cosecha.linea_guia }}</td>
                <td>{{ cosecha.camada }}</td>
                <td>{{ cosecha.nroCuelga }}</td>
                <td>{{ cosecha.metroRed }}</td>
                <td>{{ cosecha.maxiSaco }}</td>
                <td>{{ cosecha.kgsCosechado }}</td>
                <td>{{ cosecha.condicion}}</td>
                <td>{{ cosecha.nombreSembradora }}</td>
                <td>{{ cosecha.patente }}</td>
                <td>{{ cosecha.nombreDestino }}</td>
                <td class="btn-colgado" style="border-top: 0px;">
                        <a href="{{ url_for('cosecha.update', id=cosecha['idCosecha'])}}" class="action">Editar</a>
                </td>
                <td class="btn-colgado" style="border-top: 0px;">
                    <a href="{{url_for('cosecha.delete', id = cosecha['idCosecha'])}}" class="text-danger">Eliminar</a>
            </td>
            </tr> 
            {% endfor %}
        </tbody>
    </table>
    
    

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}

app/templates/cosecha/update.html
<link href="/static/assets/css/black-dashboard.css?v=1.0.0" rel="stylesheet" />


<form method="post" class="container-fluid">
    <div class="form-group row">
        <div class="col-sm-2">
            <label for="fecha">Fecha Cosecha</label>
            <input type="date" class="form-control" value="{{cosecha.fechaCosecha}}" name="fechaCosecha" id="fechaCosecha">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label for="fecha">Codigo de Centro</label>
            <input type="text" class="form-control" value="{{cosecha.codigoCentro}}" name="codigoCentro" id="codigoCentro">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label for="fecha">Numero de Guía</label>
            <input type="text" class="form-control" name="nroGuia" id="nroGuia" value="{{cosecha.nroGuia}}">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label >Folio</label>
            <input type="text" class="form-control" name="folio" id="folio"  value="{{cosecha.folio}}">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label for="fecha">Linea (Guía)</label>
            <input type="text" class="form-control" name="linea_guia" id="linea_guia" value="{{cosecha.linea_guia}}">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label for="fecha">Camada</label>
            <input type="text" class="form-control" name="camada" id="camada" value="{{cosecha.camada}}">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label for="fecha">Nro Cuelga</label>
            <input type="text" class="form-control" name="nroCuelga" id="nroCuelga" value="{{cosecha.nroCuelga}}">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label for="Metro Red">Metro Red</label>
            <input type="text" class="form-control" name="metroRed" id="metroRed" value="{{cosecha.metroRed}}">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label for="fecha">MaxiSaco</label>
            <input type="text" class="form-control" name="maxiSaco" id="maxiSaco" value="{{cosecha.maxiSaco}}">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label for="fecha">Kgs. Cosechado</label>
            <input type="text" class="form-control" name="kgsCosechado" id="kgsCosechado" value="{{cosecha.kgsCosechado}}">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label for="fecha">Condicion</label>
            <input type="text" class="form-control" name="condicion" id="condicion" value="{{cosecha.condicion}}">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <select class="form-control" name="sembradora" class="select-form" required> 
                <option value="" selected hidden >Servicio</option>
                {% for sembradora in sembradoras %}
                    <option value="{{ sembradora['idSembradora'] }}">{{ sembradora.nombreSembradora }} </option>    
                {% endfor %}
            </select> 
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label for="fecha">Patente</label>
            <input type="text" class="form-control" name="patente" id="patente" value="{{cosecha.patente}}">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <select class="form-control" name="destino" class="select-form" required> 
                <option value="" selected hidden >Destino</option>
                {% for destino in destinos %}
                    <option value="{{ destino['idDestino'] }}">{{ destino.nombreDestino }} </option>    
                {% endfor %}
            </select> 
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-1">
            <a href="{{url_for('cosecha.index')}}">Volver</a>
        </div>
        <div class="col-sm-2">
            <input type="submit" value="Guardar">
        </div>
    </div>

</form>

app/templates/includes/footer.html
<!-- 
      <footer class="footer">
        <div class="container-fluid">
          <ul class="nav">
            <li class="nav-item">
              <a target="_blank" rel="noopener noreferrer"
                 href="https://github.com/app-generator/jinja-black-dashboard" class="nav-link">
                CROSAM - Dashboard
              </a>
            </li>
          </ul>
        </div>
      </footer> -->
      

app/templates/includes/navigation.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:void(0)">CROSAM LIMITADA</a>
          </div>
          
          <div class="collapse navbar-collapse" id="navigation">


          </div>
        </div>
      </nav>
      
      <!-- End Navbar -->

app/templates/includes/scripts-sidebar.html
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');
        $navbar = $('.navbar');
        $main_panel = $('.main-panel');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');
        sidebar_mini_active = true;
        white_color = false;

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();



        $('.fixed-plugin a').click(function(event) {
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .background-color span').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data', new_color);
          }

          if ($main_panel.length != 0) {
            $main_panel.attr('data', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data', new_color);
          }
        });

        $('.switch-sidebar-mini input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            sidebar_mini_active = false;
            blackDashboard.showSidebarMessage('Sidebar mini deactivated...');
          } else {
            $('body').addClass('sidebar-mini');
            sidebar_mini_active = true;
            blackDashboard.showSidebarMessage('Sidebar mini activated...');
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);
        });

        $('.switch-change-color input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (white_color == true) {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').removeClass('white-content');
            }, 900);
            white_color = false;
          } else {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').addClass('white-content');
            }, 900);

            white_color = true;
          }


        });

        $('.light-badge').click(function() {
          $('body').addClass('white-content');
        });

        $('.dark-badge').click(function() {
          $('body').removeClass('white-content');
        });
      });
    });
  </script>
  

app/templates/includes/scripts.html
  <!--   Core JS Files   -->
  <script src="/static/assets/js/core/jquery.min.js"></script>
  <script src="/static/assets/js/core/popper.min.js"></script>
  <script src="/static/assets/js/core/bootstrap.min.js"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!-- Chart JS -->
  <script src="/static/assets/js/plugins/chartjs.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="/static/assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Black Dashboard: parallax effects, scripts for the example pages etc -->
 <!-- Black Dashboard DEMO methods, don't include it in your project! -->

  

app/templates/includes/sidebar.html
    <div class="sidebar">
      <div class="sidebar-wrapper">
        {% if g.user %}
        <div class="logo">
          <a class="simple-text logo-normal usuario"> {{ g.user['username'] }}</a>
        </div>
        {% endif %}

        <ul class="nav">
          <li>
            <a href="/">
              <i class="tim-icons icon-chart-pie-36"></i>
              <p>Dashboard</p>
            </a>
          </li>
          <li >
            <a href="{{ url_for('siembra.index') }}">
              <i class="tim-icons icon-atom"></i>
              <p>Siembra</p>
            </a>
          </li>
          <li>
            <a href="{{ url_for('colgado.index') }}">
              <i class="tim-icons icon-pin"></i>
              <p>Colgado</p>
            </a>
          </li>
          <li>
            <a href="{{ url_for('cosecha.index') }}">
              <i class="tim-icons icon-bell-55"></i>
              <p>Cosecha</p>
            </a>
          </li>
          <li>
            <a href="{{url_for('auth.logout') }}"><i class="tim-icons icon-button-power"></i>
              <p>Cerrar Sesión</p>
          </li>
        </ul>
        
      </div>
    </div>

app/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/static/assets/img/favicon.png">
  <title>
     {% block title %}{% endblock %}-CROSAM
  </title>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- Nucleo Icons -->
  <link href="/static/assets/css/nucleo-icons.css" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="/static/assets/css/black-dashboard.css?v=1.0.0" rel="stylesheet" />


  <!-- Specific Page CSS goes HERE  -->
  {% block stylesheets %}<link href="/static/assets/css/style.css" rel="stylesheet" />{% endblock stylesheets %}

</head>

<body class="">
  <div class="wrapper">

    {% include 'includes/sidebar.html' %}

    <div class="main-panel">

      {% include 'includes/navigation.html' %}

      <div class="content">

        {% block content %}
        
        {% endblock %}

      </div>

    

    </div>
    
  </div>



  {% include 'includes/scripts.html' %}

  {% include 'includes/scripts-sidebar.html' %}

  <!-- Specific Page JS goes HERE  -->
  {% block javascripts %}{% endblock javascripts %}

</body>

</html>

app/templates/page-404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pagina No Encontrada</title>
</head>
<body>
    <h1>PAGINA NO ENCONTRADA</h1>
</body>
</html>